version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cegrisa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cartagena2005
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./cegrisa
      dockerfile: Dockerfile
    volumes:
      - ./cegrisa:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./cegrisa/.env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./cegrisa_frontend
      dockerfile: Dockerfile
    volumes:
      - ./cegrisa_frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"  # accedes al frontend en localhost:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
  media_data:
